[package]
name = "nicos"
version = "0.1.0"
authors = ["Nick Chapman <nic@amadido.co.uk>"]
edition = "2018"

[profile.dev]

[profile.release]

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
